//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrintSystem.WebUI {
    
    
    public partial class index {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new FingerPrintSystem.WebUI.Master.Driver Master {
            get {
                return ((FingerPrintSystem.WebUI.Master.Driver)(base.Master));
            }
        }
    }
}
